### ISSUE TITLE
Error during Github Sign process

### ISSUE THREAD

**Issue by crosbyh** [SignTools/SignTools#140]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

I am running Signtools in Docker on my home server, and am attempting to use Github Actions as my builder. I have a paid developer account, and have set things up according to the guide. When I attempt to sign an app, the action fails with the following error message:

```
Run sudo xcode-select -s /Applications/Xcode_12.5.1.app
  sudo xcode-select -s /Applications/Xcode_12.5.1.app
  ./sign.sh
  shell: /bin/bash -e {0}
  env:
    SECRET_URL: ***
    SECRET_KEY: ***
Obtaining files...
Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/util.py", line 27, in run_process
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('tar', '-x', '-f', 'job.tar', '-C.')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 349, in <module>
    extract_tar(job_archive, Path("."))
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 85, in extract_tar
    return run_process("tar", "-x", "-f", str(archive), "-C" + str(dest_dir))
  File "/Users/runner/work/SignTools-CI/SignTools-CI/util.py", line 29, in run_process
    raise (
Exception: {'stdout': '', 'stderr': 'tar: Error opening archive: Unrecognized archive format'}
Error: Process completed with exit code 1.
```

**Expected behavior**

I'd expect the app signing to complete successfully.

**System configuration**

- SignTools version: 2.5.9
- Installation type: computer
- Builder type: [SignTools-CI
- Builder version: 89562a2

**Additional context**

**Comment by crosbyh** [comment]
I resolved this, if anybody else comes across this error code later, it was a result of a misconfigured reverse proxy. I had not properly unprotected the API endpoints in my Authelia proxy.
