### ISSUE TITLE
"Cert has expired" error - but has not...

### ISSUE THREAD

**Issue by xanthos84** [SignTools/SignTools#174]
**I tried basic troubleshooting first**
yep
- [ x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x ] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

Getting this error/output  during signing process from github ci:

`Run sudo xcode-select -s /Applications/Xcode_12.5.1.app
Initializing dependencies...
Obtaining files...
node:events:49[8](https://github.com/xanthos84/signTools/runs/5426427774?check_suite_focus=true#step:3:8)
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:[9](https://github.com/xanthos84/signTools/runs/5426427774?check_suite_focus=true#step:3:9)44:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
Emitted 'error' event on Request instance at:
    at Request.onerror (node:internal/streams/legacy:62:12)
    at Request.emit (node:events:520:28)
    at Request.onRequestError (/Users/runner/work/signTools/signTools/node-utils/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:520:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'CERT_HAS_EXPIRED'
}
Traceback (most recent call last):
  File "/Users/runner/work/signTools/signTools/util.py", line 27, in run_process
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.[10](https://github.com/xanthos84/signTools/runs/5426427774?check_suite_focus=true#step:3:10)/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('node', 'node-utils/download.js', '***/jobs', '***', 'job.tar')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/signTools/signTools/sign.py", line 373, in <module>
    node_download(secret_url + "/jobs", job_archive, capture=False)
  File "/Users/runner/work/signTools/signTools/sign.py", line [26](https://github.com/xanthos84/signTools/runs/5426427774?check_suite_focus=true#step:3:26), in node_download
    return run_process(
  File "/Users/runner/work/signTools/signTools/util.py", line [29](https://github.com/xanthos84/signTools/runs/5426427774?check_suite_focus=true#step:3:29), in run_process
    raise (
Exception: {'stdout': '', 'stderr': ''}
Error: Process completed with exit code 1.`

**Expected behavior**

signing should be going on well - as the cert.p12 and prov.mobileprovision were freshly created from xcode 10 on mac.

**System configuration**

- SignTools version: [e.g. 2.1.1]  2.5.12 linux 64 amd
- Installation type: [heroku, computer, phone; nginx, ngrok, cloudflared]:  computer/server linux
- Builder type: [SignTools-CI, SignTools-Builder] - SignToolsCI on Github
- Builder version: [e.g. 1.0.0 for SignTools-Builder; the latest commit hash of your repo for SignTools-CI, e.g. 03e0ed9] latest version forked, [b27cc98](https://github.com/xanthos84/signTools/commit/b27cc980adf0537ed29daa6fec0e73dd11945afd)

**Additional context**

I am not sure why this happens... if I try to build a app in xcode its working very well without errors.
I checked the expiration dates multiple times of the certificate, but as it was created today - its of course still one year valid.

any clues for me? :)

**Comment by ViRb3** [comment]
The HTTPS certificate you used for the SignTools service has expired, this has nothing to do with your Apple Developer certificate.

**Comment by xanthos84** [comment]
> The HTTPS certificate you used for the SignTools service has expired, this has nothing to do with your Apple Developer certificate. It simply fails to communicate to your service and download the IPA and related files.

you were so right. i was so focused on the ios certifcate that I was not thinking about the website ssl...
and i did not think about that it was relevant at all.
thanks for the hint! now its working great!
