### ISSUE TITLE
Invalid or unsupported format for signature

### ISSUE THREAD

**Issue by Keagel** [SignTools/SignTools#210]
**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

Can't sign Rocket for Instagram due to an invalid format.

**Logs**

<details>

```
Initializing dependencies...
Obtaining files...
Download finished!
Creating keychain...
Using distribution certificate
Using developer account
Logging in (1/2)...
Logging in (2/2)...
If you receive a two-factor authentication (2FA) code, please submit it to the web service.
Logged in!
Extracting app...
Signing...
Using encoded original bundle id
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Rocket.dylib
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/RIPass.dylib
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Hackogram.dylib
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/libsubstrate.dylib
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/FBSharedFramework.framework
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/CydiaSubstrate.framework
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/IGPyTorchFramework.framework
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app
Original entitlements:
{
    "application-identifier": "CLX8X3P664.com.fab.lighthouse",
    "aps-environment": "production",
    "com.apple.developer.icloud-container-development-container-identifiers": [
        "iCloud.com.fab.lighthouse"
    ],
    "com.apple.developer.icloud-container-environment": [
        "Production",
        "Development"
    ],
    "com.apple.developer.icloud-container-identifiers": [
        "iCloud.com.fab.lighthouse"
    ],
    "com.apple.developer.icloud-services": "*",
    "com.apple.developer.team-identifier": "CLX8X3P664",
    "com.apple.developer.ubiquity-container-identifiers": [
        "iCloud.com.fab.lighthouse"
    ],
    "com.apple.developer.ubiquity-kvstore-identifier": "CLX8X3P664.*",
    "get-task-allow": false,
    "keychain-access-groups": [
        "CLX8X3P664.*",
        "com.apple.token"
    ]
}
ID mappings:
{
    "CLX8X3P664": "2P5L2S79SV",
    "iCloud.com.fab.lighthouse": "iCloud.s0j.2dg.atgsizuuji"
}
Removed entitlements:
[
    "application-identifier",
    "com.apple.developer.team-identifier"
]
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Rocket.dylib
Applying patches...
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Rocket.dylib
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Rocket.dylib
Signing
Signing with original entitlements
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/RIPass.dylib
Applying patches...
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/RIPass.dylib
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/RIPass.dylib
Signing
Signing with original entitlements
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Hackogram.dylib
Applying patches...
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Hackogram.dylib
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Hackogram.dylib
Signing
Signing with original entitlements
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/libsubstrate.dylib
Applying patches...
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/libsubstrate.dylib
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/libsubstrate.dylib
Signing
Signing with original entitlements
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/FBSharedFramework.framework
Applying patches...
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/FBSharedFramework.framework/FBSharedFramework
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/FBSharedFramework.framework/FBSharedFramework
Signing
Signing with original entitlements
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/CydiaSubstrate.framework
Applying patches...
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
Signing
Signing with original entitlements
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/IGPyTorchFramework.framework
Applying patches...
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/IGPyTorchFramework.framework/IGPyTorchFramework
Patching /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/IGPyTorchFramework.framework/IGPyTorchFramework
Signing
Signing with original entitlements
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app
Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 388, in <module>
    run()
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 337, in run
    Signer(
  File "/Users/runner/work/SignTools-CI/SignTools-CI/xsign.py", line 588, in sign
    popen_check(pipe)
  File "/Users/runner/work/SignTools-CI/SignTools-CI/xsign.py", line 134, in popen_check
    raise Exception(data)
Exception: {'message': "['/usr/bin/codesign', '--continue', '-f', '--no-strict', '-s', 'Apple Distribution', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Rocket.dylib'] failed with status code 1", 'stdout': '', 'stderr': '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo6n8fcra/Payload/Instagram.app/Frameworks/Rocket.dylib: invalid or unsupported format for signature'}
==============================================
Uploading screenshot...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 16 1171k    0     0   16  192k      0   333k  0:00:03 --:--:--  0:00:03  335k

100 1171k    0   133  100 1171k    119  1054k  0:00:01  0:00:01 --:--:-- 1057k
=========================

Uploaded 1 file, 1 199 173 bytes

wget https://bashupload.com/CFhVA/test.jpg

=========================

==============================================
Cleaning up...
Error: Process completed with exit code 1.
```

</details>

**System configuration**

- SignTools version: latest
- Installation type: computer
- Builder type: SignTools-CI
- Builder version: latest commit

**Additional context**

I'm able to sign other apps, it's just this one that doesn't work. I'm trying to resign it to enable push notifications on Rocket. Do you know if this is strictly because of the app or if it's a bug?

**Comment by Keagel** [comment]
> For injecting tweaks, please get the official tweak from Cydia and inject in a clean IPA using the "Advanced" tab in SignTools.

Yeah that's what I tried. Signing works but app closes instantly whenever I add tweaks. Signing the decrypted app works and the app opens fine, but adding Rocket in any way either fails signing when I remove the jailbreak check and recompile the .dylib or just closes instantly when I try to open it. I've tried signing with the .deb file straight from a Cydia repository, from a dylib, with and without removing the jailbreak check.

I guess I'm doing something wrong if you say that it's always worked for you but I don't see what.

**Comment by ViRb3** [comment]
Oh, when I said "many official tweaks", I didn't mean your one specifically - I haven't tried that one. Remember that tweaks are made for jailbroken devices, and naturally not all will work when injected in a non-jailbroken environment, at least not without modifications. This is something for you to figure out unfortunately, since as long as SignTools is concerned, injection works properly. In your case, the tweak is most likely failing to function in a non-jailbroken environment.

**Comment by Keagel** [comment]
Rocket does work for non-jailbroken devices though, once you remove the jailbreak check - which I think I did properly as I simply followed the instructions. Either way I signed a previously working version for the time being.

When you say SignTools can inject the tweaks, do you mean the .deb files?

**Comment by ViRb3** [comment]
> fails signing when I remove the jailbreak check and recompile the .dylib

Sounds to me like you're compiling the tweak incorrectly, especially if it signs fine with the official dylib. Regarding the crash, check your crash logs. I can't offer support for individual tweaks, so unless you can track it down to a problem in SignTools, you would unfortunately be on your own. 

SignTools can inject .deb files, as well as individual frameworks and dylibs:

https://github.com/SignTools/SignTools-CI/blob/2f3ffe4d8c4f2602af31de063081f1e2c2874193/sign.py#L196

**Comment by Keagel** [comment]
> > fails signing when I remove the jailbreak check and recompile the .dylib
> 
> Sounds to me like you're compiling the tweak incorrectly, especially if it signs fine with the official dylib. Regarding the crash, check your crash logs. I can't offer support for individual tweaks, so unless you can track it down to a problem in SignTools, you would unfortunately be on your own.

No worries.

> SignTools can inject .deb files, as well as individual frameworks and dylibs:
> 
> https://github.com/SignTools/SignTools-CI/blob/2f3ffe4d8c4f2602af31de063081f1e2c2874193/sign.py#L196

Good to know, thanks.
