### ISSUE TITLE
self hosted Post i/o timeout github action problem decoding

### ISSUE THREAD

**Issue by wyq977** [SignTools/SignTools#216]
**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

## Simple

For GitHub CI, I have followed the latest guide closely and tried 2 different IPA ([Delta v1.3.1](https://github.com/rileytestut/Delta/releases/tag/1.3.1) and [RetroArch v1.10.3](https://retroarch.com/?page=platforms)). Two IPAs were signed and installed successfully with AltStore (`Version 1.5 (65)`) but I kept getting the decoding error.

```
Exception: {'stdout': '', 'stderr': 'security: failed to add data to decoder: UNKNOWN (-8183(d)\nsecurity: problem decoding'}
```

## Advanced (Self hosted)

Followed the guide closely using `cloudflared` but still get this error when running `./signtools -cloudflared-port 51881
`

This is my config for self hosted builder:

```yml
builder:
    github:
        enable: false
        repo_name: SignTools-CI
        org_name: YOUR_ORG_NAME
        workflow_file_name: sign.yml
        token: YOUR_TOKEN
        ref: master
    semaphore:
        enable: false
        project_name: YOUR_PROJECT_NAME
        org_name: YOUR_ORG_NAME
        token: YOUR_TOKEN
        ref: refs/heads/master
        secret_name: ios-signer
    selfhosted:
        enable: true
        url: http://192.168.1.133:8090
        key: mybigcock
server_url: http://192.168.1.133:8090
redirect_https: false
save_dir: data
cleanup_interval_mins: 1
sign_timeout_mins: 30
basic_auth:
    enable: false
    username: admin
    password: admin
```

**To reproduce**

**Expected behavior**

Successfully signing IPAs

**Logs**
<details><summary>Heroku Log (from GitHub Action CI "Sign")</summary><p>

```log
Run sudo xcode-select -s /Applications/Xcode_13.4.1.app
  sudo xcode-select -s /Applications/Xcode_13.4.1.app
  ./sign.sh
  shell: /bin/bash -e {0}
  env:
    SECRET_URL: ***
    SECRET_KEY: ***
Initializing dependencies...
Obtaining files...
Download finished!
Creating keychain...
Using provisioning profile
Extracting app...
Signing...
Using original bundle id
Preparing component /var/folders/[2](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:2)4/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpd5ym0gg7/Payload/Delta.app/Frameworks/Systems.framework
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpd5ym0gg7/Payload/Delta.app
Original entitlements:
{
    "application-identifier": "6XVY5G[3](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:3)U[4](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:4)4.com.rileytestut.Delta",
    "com.apple.developer.team-identifier": "6XVY[5](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:5)G3U44",
    "get-task-allow": true,
    "keychain-access-groups": [
        "[6](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:6)XVY5G3U44.com.rileytestut.Delta"
    ]
}
Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/util.py", line 2[7](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:7), in run_process
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 52[8](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:9), in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('security', 'cms', '-D', '-i', '/var/folders/24/8k48jl6d24[9](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:10)_n_qfxwsl6xvm0000gn/T/tmpd5ym0gg7/Payload/Delta.app/embedded.mobileprovision')' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 388, in <module>
    run()
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 337, in run
    Signer(
  File "/Users/runner/work/SignTools-CI/SignTools-CI/xsign.py", line 527, in sign
    job_defs.append((component, self.__prepare_primary(component, tmpdir)))
  File "/Users/runner/work/SignTools-CI/SignTools-CI/xsign.py", line 382, in __prepare_primary
    entitlements = dump_prov_entitlements(embedded_prov)
  File "/Users/runner/work/SignTools-CI/SignTools-CI/xsign.py", line 88, in dump_prov_entitlements
    return dump_prov(prov_file)["Entitlements"]
  File "/Users/runner/work/SignTools-CI/SignTools-CI/xsign.py", line 83, in dump_prov
    s = security_dump_prov(prov_file)
  File "/Users/runner/work/SignTools-CI/SignTools-CI/xsign.py", line 43, in security_dump_prov
    return decode_clean(run_process("security", "cms", "-D", "-i", str(f)).stdout)
  File "/Users/runner/work/SignTools-CI/SignTools-CI/util.py", line 29, in run_process
    raise (
Exception: {'stdout': '', 'stderr': 'security: failed to add data to decoder: UNKNOWN (-8183(d)\nsecurity: problem decoding'}
==============================================
Uploading screenshot...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 35  996k    0     0   35  352k      0   304k  0:00:03  0:00:01  0:00:02  312k
[10](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:11)0  996k    0   [13](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:14)3  100  996k     74   554k  0:00:01  0:00:01 --:--:--  564k
=========================
Uploaded 1 file, 1 0[20](https://github.com/wyq977/SignTools-CI/runs/6845866630?check_suite_focus=true#step:3:21) 076 bytes
wget https://bashupload.com/gVMlW/test.jpg
=========================
==============================================
Cleaning up...
Error: Process completed with exit code 1.
```
</p></details>

<details><summary>Self hosted Log</summary><p>

```bash
7:42AM INF obtaining server url
7:42AM INF using server url url=https://REMOVED.trycloudflare.com
7:42AM INF setting builder secrets
7:43AM FTL  error="Post \"http://192.168.1.133:8090/secrets\": dial tcp 192.168.1.133:8090: i/o timeout"
```
</p></details>

**Screenshots**

**System configuration**

- SignTools version: [2.5.17]
- Installation type: [heroku, computer: cloudflared]
- Builder type: [SignTools-CI, SignTools-Builder]
- Builder version: [SignTools-Builder: 1.1.3, SignTools-CI: 39b1a09 or 7ea9678]
- macOS version: 12.4
- iOS version: 15.3.1 iPhone 11 Pro

**Additional context**

**Comment by wyq977** [comment]
the response I saw from the server url is

```
{"message":"Not Found"}
```

**Comment by ViRb3** [comment]
It appears that the service cannot be reached on `http://192.168.1.133:8090`. Note that by default, the service is hosted on port `8080`, not `8090`. You can override this with the flag `-port 8090`, like so:
```bash
./SignTools -port 8090
```
If this doesn't help or you are already doing it, then there's another reason why the service is unreachable. That will depend on your setup, but it's likely a firewall or simply incorrect URL (IP address). Make sure you can actually access the service via `http://192.168.1.133:8090`.
