### ISSUE TITLE
Error on GitHub actions when using Fly.io

### ISSUE THREAD

**Issue by Nigel1992** [SignTools/SignTools#292]
Im trying to deploy it to Fly.io using a Enterprise Cert.
I don't know what the fly.toml contents should be since I never had an Heroku machine.
I followed the steps given here: https://github.com/SignTools/SignTools/issues/239#issuecomment-1291571332
I'm guessing its something like this ?

```
[env]
BASIC_AUTH_ENABLE = "true"
BASIC_AUTH_PASSWORD = "mypassword"
BASIC_AUTH_USERNAME = "myusername"
BUILDER_GITHUB_ENABLE = "true"
BUILDER_GITHUB_ORG_NAME = "Nigel1992"
BUILDER_GITHUB_REF = "master"
BUILDER_GITHUB_REPO_NAME = "SignToolsCI"
BUILDER_GITHUB_TOKEN = "private"
BUILDER_GITHUB_WORKFLOW_FILE_NAME = "sign.yml"
PROFILE_ACCOUNT_NAME = ""
PROFILE_ACCOUNT_PASS = ""
PROFILE_CERT_BASE64 = "private"
PROFILE_CERT_PASS = "123"
PROFILE_NAME = "MyiPhone"
PROFILE_PROV_BASE64 = "private"
REDIRECT_HTTPS = "true"
SERVER_URL = "idk?"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

What do I pick for server url?
So far, I am able to launch the WebUI, but it wont sign.
Sign errors out on GitHub actions.

![image](https://user-images.githubusercontent.com/5491930/219844375-e279563d-8897-4628-889b-dd1d589d0fc4.png)

```
Run sudo xcode-select -s /Applications/Xcode_14.0.1.app
connect ECONNREFUSED ::1:[8](https://github.com/Nigel1992/SignToolsCi/actions/runs/4209790132/jobs/7307005755#step:3:9)080
Traceback (most recent call last):
Initializing dependencies...
  File "/Users/runner/work/SignToolsCi/SignToolsCi/./sign.py", line 48, in run_process
Downloading job files...
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.[11](https://github.com/Nigel1992/SignToolsCi/actions/runs/4209790132/jobs/7307005755#step:3:12)/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('node', 'node-utils/download.js', '***/jobs', '***', 'job.tar')' returned non-zero exit status 3.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/SignToolsCi/SignToolsCi/./sign.py", line 1160, in <module>
    node_download(secret_url + "/jobs", job_archive, capture=False)
  File "/Users/runner/work/SignToolsCi/SignToolsCi/./sign.py", line [13](https://github.com/Nigel1992/SignToolsCi/actions/runs/4209790132/jobs/7307005755#step:3:14)8, in node_download
    return run_process(
           ^^^^^^^^^^^^
  File "/Users/runner/work/SignToolsCi/SignToolsCi/./sign.py", line 50, in run_process
    raise (
Exception: {'stdout': '', 'stderr': ''}
Error: Process completed with exit code 1.

app = "private"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
```

**Comment by ViRb3** [comment]
Closing since it's unrelated to SignTools and rather a problem with Fly.io, but feel free to continue any discussion here or in the issue above.
