### ISSUE TITLE
failed to sign  localhost windows

### ISSUE THREAD

**Issue by SkySoyu** [SignTools/SignTools#297]
2023-03-02T01:35:47.2600540Z ##[group]Run sudo xcode-select -s /Applications/Xcode_14.0.1.app
2023-03-02T01:35:47.2601370Z [36;1msudo xcode-select -s /Applications/Xcode_14.0.1.app[0m
2023-03-02T01:35:47.2602090Z [36;1m./sign.py[0m
2023-03-02T01:35:47.2777750Z shell: /bin/bash -e {0}
2023-03-02T01:35:47.2778170Z env:
2023-03-02T01:35:47.2779360Z   SECRET_URL: ***
2023-03-02T01:35:47.2779870Z   SECRET_KEY: ***
2023-03-02T01:35:47.2780220Z ##[endgroup]
2023-03-02T01:35:50.8843240Z connect ECONNREFUSED ::1:8080
2023-03-02T01:35:50.8844420Z Traceback (most recent call last):
2023-03-02T01:35:50.8912390Z Initializing dependencies...
2023-03-02T01:35:50.8940620Z   File "/Users/runner/work/ios-signer-drakos/ios-signer-drakos/./sign.py", line 48, in run_process
2023-03-02T01:35:50.9012810Z Downloading job files...
2023-03-02T01:35:50.9033810Z     result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
2023-03-02T01:35:50.9086720Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-02T01:35:50.9129110Z   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
2023-03-02T01:35:50.9156750Z     raise CalledProcessError(retcode, process.args,
2023-03-02T01:35:50.9199250Z subprocess.CalledProcessError: Command '('node', 'node-utils/download.js', '***/jobs', '***', 'job.tar')' returned non-zero exit status 3.
2023-03-02T01:35:50.9233740Z 
2023-03-02T01:35:50.9261960Z The above exception was the direct cause of the following exception:
2023-03-02T01:35:50.9292190Z 
2023-03-02T01:35:50.9321680Z Traceback (most recent call last):
2023-03-02T01:35:50.9349480Z   File "/Users/runner/work/ios-signer-drakos/ios-signer-drakos/./sign.py", line 1160, in <module>
2023-03-02T01:35:50.9376120Z     node_download(secret_url + "/jobs", job_archive, capture=False)
2023-03-02T01:35:50.9403900Z   File "/Users/runner/work/ios-signer-drakos/ios-signer-drakos/./sign.py", line 138, in node_download
2023-03-02T01:35:50.9430150Z     return run_process(
2023-03-02T01:35:50.9456290Z            ^^^^^^^^^^^^
2023-03-02T01:35:50.9483290Z   File "/Users/runner/work/ios-signer-drakos/ios-signer-drakos/./sign.py", line 50, in run_process
2023-03-02T01:35:50.9506190Z     raise (
2023-03-02T01:35:50.9561240Z Exception: {'stdout': '', 'stderr': ''}
2023-03-02T01:35:50.9609270Z ##[error]Process completed with exit code 1.

**Comment by SkySoyu** [comment]
whats wrong

**Comment by ViRb3** [comment]
Please follow the template.
